# Generated by Django 3.1.1 on 2021-04-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_sell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
